In [ ]:

import pandas as pd
dfbank=pd.read_csv('https://raw.githubusercontent.com/jarsmp37/introds/main/Churn_Bank.csv')
dfbank

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Complain,Satisfaction Score,Card Type,Point Earned
0,1.0,15634602.0,Hargrave,619,France,Female,NaN,2,0.0,1.0,1,1,101348.88,1,1,2,DIAMOND,464
1,2.0,15647311.0,Hill,608,Spain,Female,41.0,1,83807.86,1.0,0,1,112542.58,0,1,3,DIAMOND,456
2,3.0,15619304.0,Onio,502,France,Female,42.0,8,159660.8,3.0,1,0,113931.57,NaN,1,3,DIAMOND,377
3,4.0,15701354.0,Boni,699,France,Female,39.0,1,0.0,2.0,0,0,93826.63,0,invalid_value,5,GOLD,350
4,5.0,15737888.0,Mitchell,850,Spain,Female,NaN,2,125510.82,1.0,1,1,invalid_value,0,0,5,GOLD,425
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12200,7026.0,15711446.0,Sinclair,569,Spain,Female,51.0,3,0.0,3.0,1,0,75084.96,1,1,2,SILVER,NaN
12201,1272.0,15793854.0,Ahmed,723,France,Male,42.0,2,99095.73,1.0,1,1,17512.53,0,0,3,DIAMOND,505
12202,4942.0,15715047.0,Joshua,640,invalid_value,Male,43.0,9,172478.15,1.0,1,0,191084.4,1,1,4,DIAMOND,844
12203,8299.0,15605534.0,Turnbull,644,Germany,Female,51.0,4,95560.04,1.0,0,0,72628.84,1,1,1,PLATINUM,672
12204,1689.0,15804610.0,Valdez,601,France,Female,41.0,1,0.0,2.0,0,1,160607.06,0,0,4,SILVER,856

In [ ]:
dfbank1=dfbank.dropna()

In [ ]:
columnas=['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited', 'Complain',
       'Satisfaction Score', 'Card Type', 'Point Earned']

In [ ]:

dfbank2 = dfbank1
for v in columnas:
  dfbank2 = dfbank2[dfbank2[v]!='invalid_value']

In [ ]:
dfbank2.isnull().sum()

RowNumber             0
CustomerId            0
Surname               0
CreditScore           0
Geography             0
Gender                0
Age                   0
Tenure                0
Balance               0
NumOfProducts         0
HasCrCard             0
IsActiveMember        0
EstimatedSalary       0
Exited                0
Complain              0
Satisfaction Score    0
Card Type             0
Point Earned          0
dtype: int64

In [ ]:


for c in columnas:
    print(f"{c}: {dfbank2[dfbank2[c]=='invalid_value'].shape[0]}")

RowNumber: 0
CustomerId: 0
Surname: 0
CreditScore: 0
Geography: 0
Gender: 0
Age: 0
Tenure: 0
Balance: 0
NumOfProducts: 0
HasCrCard: 0
IsActiveMember: 0
EstimatedSalary: 0
Exited: 0
Complain: 0
Satisfaction Score: 0
Card Type: 0
Point Earned: 0

In [ ]:
dfbank2

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Complain,Satisfaction Score,Card Type,Point Earned
1,2.0,15647311.0,Hill,608,Spain,Female,41.0,1,83807.86,1.0,0,1,112542.58,0,1,3,DIAMOND,456
5,6.0,15574012.0,Chu,645,Spain,Male,44.0,8,113755.78,2.0,1,0,149756.71,1,1,5,DIAMOND,484
6,7.0,15592531.0,Bartlett,822,France,Male,50.0,7,0.0,2.0,1,1,10062.8,0,0,2,SILVER,206
7,8.0,15656148.0,Obinna,376,Germany,Female,29.0,4,115046.74,4.0,1,0,119346.88,1,1,2,DIAMOND,282
8,9.0,15792365.0,He,501,France,Male,44.0,4,142051.07,2.0,0,1,74940.5,0,0,3,GOLD,251
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12198,6261.0,15672826.0,Chen,666,France,Female,32.0,10,112536.57,2.0,1,1,34350.54,0,0,3,SILVER,281
12199,2271.0,15622217.0,Tu,538,France,Female,38.0,8,88758.95,2.0,0,0,28226.15,1,1,1,DIAMOND,911
12201,1272.0,15793854.0,Ahmed,723,France,Male,42.0,2,99095.73,1.0,1,1,17512.53,0,0,3,DIAMOND,505
12203,8299.0,15605534.0,Turnbull,644,Germany,Female,51.0,4,95560.04,1.0,0,0,72628.84,1,1,1,PLATINUM,672
12204,1689.0,15804610.0,Valdez,601,France,Female,41.0,1,0.0,2.0,0,1,160607.06,0,0,4,SILVER,856

In [ ]:
dfbank3 = dfbank2.drop_duplicates(subset=['CustomerId'])
dfbank3

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Complain,Satisfaction Score,Card Type,Point Earned
1,2.0,15647311.0,Hill,608,Spain,Female,41.0,1,83807.86,1.0,0,1,112542.58,0,1,3,DIAMOND,456
5,6.0,15574012.0,Chu,645,Spain,Male,44.0,8,113755.78,2.0,1,0,149756.71,1,1,5,DIAMOND,484
6,7.0,15592531.0,Bartlett,822,France,Male,50.0,7,0.0,2.0,1,1,10062.8,0,0,2,SILVER,206
7,8.0,15656148.0,Obinna,376,Germany,Female,29.0,4,115046.74,4.0,1,0,119346.88,1,1,2,DIAMOND,282
8,9.0,15792365.0,He,501,France,Male,44.0,4,142051.07,2.0,0,1,74940.5,0,0,3,GOLD,251
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11915,479.0,15677538.0,Nwokike,569,France,Male,38.0,7,0.0,1.0,1,1,108469.2,0,0,5,SILVER,550
11920,618.0,15766575.0,Larionova,612,Germany,Female,62.0,8,140745.33,1.0,1,0,193437.89,1,1,5,GOLD,455
11991,7229.0,15707602.0,Macleod,539,France,Female,47.0,2,127286.04,2.0,1,1,166929.43,1,1,1,DIAMOND,551
12088,9435.0,15733229.0,Rodriguez,638,Spain,Female,34.0,7,0.0,2.0,0,0,3946.29,0,0,2,PLATINUM,504
12167,9945.0,15703923.0,Cameron,744,Germany,Male,41.0,7,190409.34,2.0,1,1,138361.48,0,0,3,PLATINUM,915

In [ ]:
dfbank3=dfbank3.rename(columns={'Surname': 'Apellido','Geography': 'Pais','Gender': 'Género','Age': 'Edad','Tenure': 'Estadía','NumOfProducts': '#Productos','HasCrCard': 'Tarjeta_Credito','IsActiveMember': 'Activo','EstimatedSalary': 'Salario', 'Exited': 'Salida', 'Complain': 'Quejas', 'Satisfaction Score': 'Nivel_Satisfacción', 'Card Type': 'Tipo_Tarjeta', 'Point Earned': 'Puntos'})

In [ ]:
dfbank3

,RowNumber,CustomerId,Apellido,CreditScore,Pais,Género,Edad,Estadía,Balance,#Productos,Tarjeta_Credito,Activo,Salario,Salida,Quejas,Nivel_Satisfacción,Tipo_Tarjeta,Puntos
1,2.0,15647311.0,Hill,608,Spain,Female,41.0,1,83807.86,1.0,0,1,112542.58,0,1,3,DIAMOND,456
5,6.0,15574012.0,Chu,645,Spain,Male,44.0,8,113755.78,2.0,1,0,149756.71,1,1,5,DIAMOND,484
6,7.0,15592531.0,Bartlett,822,France,Male,50.0,7,0.0,2.0,1,1,10062.8,0,0,2,SILVER,206
7,8.0,15656148.0,Obinna,376,Germany,Female,29.0,4,115046.74,4.0,1,0,119346.88,1,1,2,DIAMOND,282
8,9.0,15792365.0,He,501,France,Male,44.0,4,142051.07,2.0,0,1,74940.5,0,0,3,GOLD,251
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11915,479.0,15677538.0,Nwokike,569,France,Male,38.0,7,0.0,1.0,1,1,108469.2,0,0,5,SILVER,550
11920,618.0,15766575.0,Larionova,612,Germany,Female,62.0,8,140745.33,1.0,1,0,193437.89,1,1,5,GOLD,455
11991,7229.0,15707602.0,Macleod,539,France,Female,47.0,2,127286.04,2.0,1,1,166929.43,1,1,1,DIAMOND,551
12088,9435.0,15733229.0,Rodriguez,638,Spain,Female,34.0,7,0.0,2.0,0,0,3946.29,0,0,2,PLATINUM,504
12167,9945.0,15703923.0,Cameron,744,Germany,Male,41.0,7,190409.34,2.0,1,1,138361.48,0,0,3,PLATINUM,915

In [ ]:
dfbank3['Pais'].unique()

array(['Spain', 'France', 'Germany'], dtype=object)

In [ ]:

traduccion={
   'Spain':'España',
   'France':'Francia',
   'Germany':'Alemania'
}

In [ ]:

dfbank3["Pais"]=dfbank3["Pais"].replace(traduccion)

In [ ]:
dfbank3['Género'].unique()

array(['Female', 'Male'], dtype=object)

In [ ]:


traduccion2={
   'Female':'Mujer',
   'Male':'Hombre'
}

In [ ]:


dfbank3["Género"]=dfbank3["Género"].replace(traduccion2)
dfbank3

,RowNumber,CustomerId,Apellido,CreditScore,Pais,Género,Edad,Estadía,Balance,#Productos,Tarjeta_Credito,Activo,Salario,Salida,Quejas,Nivel_Satisfacción,Tipo_Tarjeta,Puntos
1,2.0,15647311.0,Hill,608,España,Mujer,41.0,1,83807.86,1.0,0,1,112542.58,0,1,3,DIAMOND,456
5,6.0,15574012.0,Chu,645,España,Hombre,44.0,8,113755.78,2.0,1,0,149756.71,1,1,5,DIAMOND,484
6,7.0,15592531.0,Bartlett,822,Francia,Hombre,50.0,7,0.0,2.0,1,1,10062.8,0,0,2,SILVER,206
7,8.0,15656148.0,Obinna,376,Alemania,Mujer,29.0,4,115046.74,4.0,1,0,119346.88,1,1,2,DIAMOND,282
8,9.0,15792365.0,He,501,Francia,Hombre,44.0,4,142051.07,2.0,0,1,74940.5,0,0,3,GOLD,251
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11915,479.0,15677538.0,Nwokike,569,Francia,Hombre,38.0,7,0.0,1.0,1,1,108469.2,0,0,5,SILVER,550
11920,618.0,15766575.0,Larionova,612,Alemania,Mujer,62.0,8,140745.33,1.0,1,0,193437.89,1,1,5,GOLD,455
11991,7229.0,15707602.0,Macleod,539,Francia,Mujer,47.0,2,127286.04,2.0,1,1,166929.43,1,1,1,DIAMOND,551
12088,9435.0,15733229.0,Rodriguez,638,España,Mujer,34.0,7,0.0,2.0,0,0,3946.29,0,0,2,PLATINUM,504
12167,9945.0,15703923.0,Cameron,744,Alemania,Hombre,41.0,7,190409.34,2.0,1,1,138361.48,0,0,3,PLATINUM,915

In [ ]:
dfbank3['CustomerId']=dfbank3['CustomerId'].astype(float).astype(int)
dfbank3['Edad']=dfbank3['Edad'].astype(float).astype(int)
dfbank3['Estadía']=dfbank3['Estadía'].astype(float).astype(int)
dfbank3['Nivel_Satisfacción']=dfbank3['Nivel_Satisfacción'].astype(float).astype(int)
dfbank3['Puntos']=dfbank3['Puntos'].astype(float).astype(int)
dfbank3['Salida']=dfbank3['Salida'].astype(float).astype(int)
dfbank3['Quejas']=dfbank3['Quejas'].astype(float).astype(int)
dfbank3['#Productos']=dfbank3['#Productos'].astype(float).astype(int)
dfbank3['Tarjeta_Credito']=dfbank3['Tarjeta_Credito'].astype(float).astype(int)
dfbank3['Activo']=dfbank3['Activo'].astype(float).astype(int)

In [ ]:
dfbank3['Balance']=dfbank3['Balance'].astype(float)
dfbank3['Salario']=dfbank3['Salario'].astype(float)

In [ ]:
dfbank3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6664 entries, 1 to 12167
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   RowNumber           6664 non-null   object
 1   CustomerId          6664 non-null   int64
 2   Apellido            6664 non-null   object
 3   CreditScore         6664 non-null   object
 4   Pais                6664 non-null   object
 5   Género              6664 non-null   object
 6   Edad                6664 non-null   int64
 7   Estadía             6664 non-null   int64
 8   Balance             6664 non-null   float64
 9   #Productos          6664 non-null   int64
 10  Tarjeta_Credito     6664 non-null   int64
 11  Activo              6664 non-null   int64
 12  Salario             6664 non-null   float64
 13  Salida              6664 non-null   int64
 14  Quejas              6664 non-null   int64
 15  Nivel_Satisfacción  6664 non-null   int64
 16  Tipo_Tarjeta        6664 non-null   object
 17  Puntos              6664 non-null   int64
dtypes: float64(2), int64(10), object(6)
memory usage: 989.2+ KB

In [ ]:
dfbank4=dfbank3.drop(columns=['RowNumber'])

In [ ]:
dfbank4=dfbank4.reset_index(drop=True)

In [ ]:
dfbank4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6664 entries, 0 to 6663
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CustomerId          6664 non-null   int64
 1   Apellido            6664 non-null   object
 2   CreditScore         6664 non-null   object
 3   Pais                6664 non-null   object
 4   Género              6664 non-null   object
 5   Edad                6664 non-null   int64
 6   Estadía             6664 non-null   int64
 7   Balance             6664 non-null   float64
 8   #Productos          6664 non-null   int64
 9   Tarjeta_Credito     6664 non-null   int64
 10  Activo              6664 non-null   int64
 11  Salario             6664 non-null   float64
 12  Salida              6664 non-null   int64
 13  Quejas              6664 non-null   int64
 14  Nivel_Satisfacción  6664 non-null   int64
 15  Tipo_Tarjeta        6664 non-null   object
 16  Puntos              6664 non-null   int64
dtypes: float64(2), int64(10), object(5)
memory usage: 885.2+ KB

In [ ]:
dfbank4

,CustomerId,Apellido,CreditScore,Pais,Género,Edad,Estadía,Balance,#Productos,Tarjeta_Credito,Activo,Salario,Salida,Quejas,Nivel_Satisfacción,Tipo_Tarjeta,Puntos
0,15647311,Hill,608,España,Mujer,41,1,83807.86,1,0,1,112542.58,0,1,3,DIAMOND,456
1,15574012,Chu,645,España,Hombre,44,8,113755.78,2,1,0,149756.71,1,1,5,DIAMOND,484
2,15592531,Bartlett,822,Francia,Hombre,50,7,0.00,2,1,1,10062.80,0,0,2,SILVER,206
3,15656148,Obinna,376,Alemania,Mujer,29,4,115046.74,4,1,0,119346.88,1,1,2,DIAMOND,282
4,15792365,He,501,Francia,Hombre,44,4,142051.07,2,0,1,74940.50,0,0,3,GOLD,251
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6659,15677538,Nwokike,569,Francia,Hombre,38,7,0.00,1,1,1,108469.20,0,0,5,SILVER,550
6660,15766575,Larionova,612,Alemania,Mujer,62,8,140745.33,1,1,0,193437.89,1,1,5,GOLD,455
6661,15707602,Macleod,539,Francia,Mujer,47,2,127286.04,2,1,1,166929.43,1,1,1,DIAMOND,551
6662,15733229,Rodriguez,638,España,Mujer,34,7,0.00,2,0,0,3946.29,0,0,2,PLATINUM,504
6663,15703923,Cameron,744,Alemania,Hombre,41,7,190409.34,2,1,1,138361.48,0,0,3,PLATINUM,915

In [ ]:
dfbank4.to_csv("Base_Chunk_Limpia.csv", index=[True])